language:
  - node_js
node_js:
  - "12.18.3"
cashe:
  directories:
    - node_modules
script:
  - npm run test jest --passWithNoTests

# whitelist
branches:
  only:
    - master
    - simplification

